services:
  backend_nginx:
    image: nginx:1.25
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "7000:80"

  backend_php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
        # extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      # - host.docker.internal:host-gateway
  frontend:
    image: httpd:2.4
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
        - "4000:80"

